
services:
  frontend:
    build: ./frontend
    image: affciak/frontend:latest
    environment:
      - REDIRECT_URL=${REDIRECT_URL}
      - API_URL=${API_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
    ports:
      - "80:80"
    depends_on:
      - backend
      
  role-service:
    build: ./role-service
    image: affciak/role-service:latest
    environment:
      - DOCKER_ENV=production
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    hostname: backend
    image: affciak/backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.production
    environment:
      - DOCKER_ENV=production
      - REDIRECT_URL=${REDIRECT_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - ROLE_SERVICE_URL=${ROLE_SERVICE_URL}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    restart: always
    hostname: db
    ports:
      - "7777:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5


volumes:
  mysql_data: