
services:
  frontend:
    build: ./frontend
    image: affciak/frontend:latest
    environment: 
      - API_URL=http://backend:8000
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    hostname: backend
    image: affciak/backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.production
    environment:
      - DOCKER_ENV=production
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    restart: always
    hostname: db
    ports:
      - "7777:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5


volumes:
  mysql_data: